### ISSUE TITLE
Check French in new figures

### ISSUE THREAD

**Issue by alburycatalina** [klaxonklaxoff/ee_dv#2]

**Comment by klaxonklaxoff** [comment]
Tweaked French where I thought we needed to. If we have time, normally in French we use commas instead of periods but that would mean changing the class from character to numeric. It's not a big deal if we don't do this though.

**Comment by alburycatalina** [comment]
Found this guy: options(OutDec= "."). It changes the decimal separator to commas for plots. Much simpler than I thought it would be :-)

**Comment by alburycatalina** [comment]
https://stackoverflow.com/questions/71430715/is-there-an-option-to-set-as-default-decimal-point-for-axis-labels-in-ggplot
